{
 "openapi": "3.0.0",
 "x-generator": "Dynamic OpenAPI Generator v1.0.0",
 "info": {
  "title": "bunny.net Compute API",
  "description": "<img src='https://bunny.net/v2/images/bunnynet-logo-dark.svg' style='width: 200px;' alt='bunny.net Logo'>\n               Edge Scripts and Compute API documentation for bunny.net. This API provides endpoints for managing edge scripts, releases, secrets, variables, and other compute-related resources.",
  "termsOfService": "https://bunny.net/tos",
  "contact": {
   "name": "bunny.net",
   "url": "https://docs.bunny.net",
   "email": "support@bunny.net"
  },
  "version": "1.0.0"
 },
 "servers": [
  {
   "url": "https://api.bunny.net",
   "description": "bunny.net API Server"
  }
 ],
 "paths": {
  "/compute/script": {
   "get": {
    "tags": [
     "Edge Script"
    ],
    "summary": "List Edge Scripts",
    "operationId": "ListEdgeScripts_ListEdgeScriptsByAccount",
    "security": [
     {
      "AccessKey": [
       "SubuserAPIManage",
       "SubuserAPIPullZones",
       "SubuserManage",
       "SubuserPullZones",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The list of scripts on the account."
   },
   "post": {
    "tags": [
     "Edge Script"
    ],
    "summary": "AddScript",
    "operationId": "CreateEdgeScript_AddScript",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ]
   }
  },
  "/compute/script/{id}/statistics": {
   "get": {
    "tags": [
     "Edge Script"
    ],
    "summary": "Get Edge Script Statistics",
    "operationId": "EdgeScriptStatistics_GetEdgeScriptStatisticsEndpoint",
    "security": [
     {
      "AccessKey": [
       "SubuserAPIManage",
       "SubuserAPIStatistics",
       "SubuserManage",
       "SubuserStatistics",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "Returns the statistics for the Edge Script with the given ID"
   }
  },
  "/compute/script/{id}": {
   "get": {
    "tags": [
     "Edge Script"
    ],
    "summary": "Get Edge Script",
    "operationId": "GetEdgeScriptById_GetEdgeScriptById",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The script with the requested ID"
   },
   "delete": {
    "tags": [
     "Edge Script"
    ],
    "summary": "Delete Edge Script",
    "operationId": "DeleteEdgeScript_Delete",
    "security": [
     {
      "AccessKey": [
       "SubuserAPIManage",
       "SubuserAPIPullZones",
       "SubuserManage",
       "SubuserPullZones",
       "User",
       "UserApi"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Edge Script"
    ],
    "summary": "Update Edge Script",
    "operationId": "UpdateEdgeScript_Update",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The script with the requested ID"
   }
  },
  "/compute/script/{id}/deploymentKey/rotate": {
   "post": {
    "tags": [
     "Edge Script"
    ],
    "summary": "Rotate Deployment Key",
    "operationId": "RotateEdgeScriptDeploymentKey_RotateEdgeScriptDeploymentKey",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ]
   }
  },
  "/compute/script/{id}/secrets/{secretId}": {
   "delete": {
    "tags": [
     "Secret"
    ],
    "summary": "Delete Secret",
    "operationId": "DeleteEdgeScriptSecret_DeleteSecret",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Secret"
    ],
    "summary": "Update Secret",
    "operationId": "UpdateEdgeScriptSecret_UpdateEdgeScriptSecret",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The script with the requested ID"
   }
  },
  "/compute/script/{id}/secrets": {
   "get": {
    "tags": [
     "Secret"
    ],
    "summary": "List Secrets",
    "operationId": "ListEdgeScriptSecrets_ListEdgeScriptSecrets",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The list of secrets for the script."
   },
   "post": {
    "tags": [
     "Secret"
    ],
    "summary": "Add Secret",
    "operationId": "AddEdgeScriptSecret_AddEdgeScriptSecret",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The script with the requested ID"
   },
   "put": {
    "tags": [
     "Secret"
    ],
    "summary": "Upsert Secret",
    "operationId": "UpsertEdgeScriptSecret_UpsertEdgeScriptSecret",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "A new secret was created"
   }
  },
  "/compute/script/{id}/variables/{variableId}": {
   "get": {
    "tags": [
     "Variable"
    ],
    "summary": "Get Variable",
    "operationId": "GetEdgeScriptVariable_GetVariable",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The script with the requested ID"
   },
   "delete": {
    "tags": [
     "Variable"
    ],
    "summary": "Delete Variable",
    "operationId": "DeleteEdgeScriptVariable_DeleteVariable",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Variable"
    ],
    "summary": "Update Variable",
    "operationId": "UpdateEdgeScriptVariable_UpdateVariable",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The script with the requested ID"
   }
  },
  "/compute/script/{id}/variables": {
   "put": {
    "tags": [
     "Variable"
    ],
    "summary": "Upsert Variable",
    "operationId": "UpsertEdgeScriptVariable_UpsertEdgeScriptVariable",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The variable was created"
   }
  },
  "/compute/script/{id}/variables/add": {
   "post": {
    "tags": [
     "Variable"
    ],
    "summary": "Add Variable",
    "operationId": "AddEdgeScriptVariable_AddEdgeScriptVariable",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The script with the requested ID"
   }
  },
  "/compute/script/{id}/code": {
   "post": {
    "tags": [
     "Code"
    ],
    "summary": "Set Code",
    "operationId": "UploadEdgeScriptCode_SetCode",
    "security": [
     {
      "AccessKey": [
       "SubuserAPICompute",
       "SubuserAPIDns",
       "SubuserAPIManage",
       "SubuserCompute",
       "SubuserManage",
       "User",
       "UserApi"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Code"
    ],
    "summary": "Get Code",
    "operationId": "GetEdgeScriptCode_GetCode",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "The code of the script with the requested ID"
   }
  },
  "/compute/script/{id}/publish": {
   "post": {
    "tags": [
     "Release"
    ],
    "summary": "Publish Release",
    "operationId": "PublishEdgeScriptRelease_Publish",
    "security": [
     {
      "AccessKey": [
       "SubuserAPICompute",
       "SubuserAPIDns",
       "SubuserAPIManage",
       "SubuserCompute",
       "SubuserManage",
       "User",
       "UserApi"
      ]
     }
    ]
   }
  },
  "/compute/script/{id}/publish/{uuid}": {
   "post": {
    "tags": [
     "Release"
    ],
    "summary": "Publish Release",
    "operationId": "PublishEdgeScriptRelease_Publish2",
    "security": [
     {
      "AccessKey": [
       "SubuserAPICompute",
       "SubuserAPIDns",
       "SubuserAPIManage",
       "SubuserCompute",
       "SubuserManage",
       "User",
       "UserApi"
      ]
     }
    ]
   }
  },
  "/compute/script/{id}/releases/active": {
   "get": {
    "tags": [
     "Release"
    ],
    "summary": "Get Active Release",
    "operationId": "GetEdgeScriptActiveRelease_GetCurrentlyActiveReleaseEndpoint",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "Currently active release of the script with the requested ID"
   }
  },
  "/compute/script/{id}/releases": {
   "get": {
    "tags": [
     "Release"
    ],
    "summary": "Get Releases",
    "operationId": "GetEdgeScriptRelease_GetReleases",
    "security": [
     {
      "AccessKey": [
       "Subuser",
       "User",
       "UserApi"
      ]
     }
    ],
    "description": "Published releases of the script with the requested ID"
   }
  }
 },
 "components": {
  "securitySchemes": {
   "AccessKey": {
    "type": "apiKey",
    "description": "API Access Key authorization header",
    "name": "AccessKey",
    "in": "header"
   }
  }
 }
}